name: first_document

on:
    push:
        branches: ["main"]
    pull_request: 
        branches: ["main"]

env:
    prj_name: Project

jobs:
    build:
        runs-on: ubuntu-latest
      
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
      
            - name: Build HTML
              run: |
                echo '<!DOCTYPE html>' > index.html
                echo '<html lang="en">' >> index.html
                echo '<head></head>' >> index.html
                echo '<body>' >> index.html
                echo '    <p>Hello world!</p>' >> index.html
                echo '</body>' >> index.html
                echo '</html>' >> index.html
      
            - name: Deploy to GitHub Pages
              run: |
                git config --global user.name 'GitHub Actions'
                git config --global user.email 'actions@github.com'
                git add index.html
                git commit -m 'Build HTML'
                git push